# Generated by Django 4.2.2 on 2023-06-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('district', models.TextField()),
                ('branch', models.TextField()),
                ('account_type', models.TextField()),
                ('mater_provi', models.TextField()),
            ],
        ),
    ]
